# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_project/MY_Basys-3-Master.xdc

# Block Designs: bd/design_mb_tg/design_mb_tg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg || ORIG_REF_NAME==design_mb_tg} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_microblaze_0_0/design_mb_tg_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_microblaze_0_0 || ORIG_REF_NAME==design_mb_tg_microblaze_0_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_dlmb_v10_0/design_mb_tg_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_dlmb_v10_0 || ORIG_REF_NAME==design_mb_tg_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_ilmb_v10_0/design_mb_tg_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_ilmb_v10_0 || ORIG_REF_NAME==design_mb_tg_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_dlmb_bram_if_cntlr_0/design_mb_tg_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_mb_tg_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_ilmb_bram_if_cntlr_0/design_mb_tg_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_mb_tg_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_lmb_bram_0/design_mb_tg_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_lmb_bram_0 || ORIG_REF_NAME==design_mb_tg_lmb_bram_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_mdm_1_0/design_mb_tg_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_mdm_1_0 || ORIG_REF_NAME==design_mb_tg_mdm_1_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_clk_wiz_1_0/design_mb_tg_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_clk_wiz_1_0 || ORIG_REF_NAME==design_mb_tg_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_rst_clk_wiz_1_100M_0/design_mb_tg_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_mb_tg_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_axi_gpio_0_0/design_mb_tg_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_axi_gpio_0_0 || ORIG_REF_NAME==design_mb_tg_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_axi_gpio_1_0/design_mb_tg_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_axi_gpio_1_0 || ORIG_REF_NAME==design_mb_tg_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_axi_uartlite_0_0/design_mb_tg_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_axi_uartlite_0_0 || ORIG_REF_NAME==design_mb_tg_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_xbar_0/design_mb_tg_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_xbar_0 || ORIG_REF_NAME==design_mb_tg_xbar_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_microblaze_0_axi_periph_0/design_mb_tg_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_mb_tg_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_AXI4_TickGenerator_0_0/design_mb_tg_AXI4_TickGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_AXI4_TickGenerator_0_0 || ORIG_REF_NAME==design_mb_tg_AXI4_TickGenerator_0_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_axi_gpio_2_0/design_mb_tg_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_axi_gpio_2_0 || ORIG_REF_NAME==design_mb_tg_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_mb_tg/ip/design_mb_tg_AXI4_fndController_0_2/design_mb_tg_AXI4_fndController_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_tg_AXI4_fndController_0_2 || ORIG_REF_NAME==design_mb_tg_AXI4_fndController_0_2} -quiet] -quiet

# XDC: bd/design_mb_tg/design_mb_tg_ooc.xdc
