# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/FPGA_project/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator.srcs/sources_1/bd/design_mb_tg/ip/design_mb_tg_ilmb_v10_0/design_mb_tg_ilmb_v10_0.xci
# IP: The module: 'design_mb_tg_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA_project/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator.srcs/sources_1/bd/design_mb_tg/ip/design_mb_tg_ilmb_v10_0/design_mb_tg_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_tg_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/FPGA_project/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator.srcs/sources_1/bd/design_mb_tg/ip/design_mb_tg_ilmb_v10_0/design_mb_tg_ilmb_v10_0.xci
# IP: The module: 'design_mb_tg_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA_project/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator/MicroBlaze_tickGenerator.srcs/sources_1/bd/design_mb_tg/ip/design_mb_tg_ilmb_v10_0/design_mb_tg_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_tg_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
