# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_project/MY_Basys-3-Master.xdc

# Block Designs: bd/design_microblaze_gpio/design_microblaze_gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio || ORIG_REF_NAME==design_microblaze_gpio} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_microblaze_0_0/design_microblaze_gpio_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_microblaze_0_0 || ORIG_REF_NAME==design_microblaze_gpio_microblaze_0_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_gpio_0_0/design_microblaze_gpio_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_axi_gpio_0_0 || ORIG_REF_NAME==design_microblaze_gpio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_axi_uartlite_0_0 || ORIG_REF_NAME==design_microblaze_gpio_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_dlmb_v10_0/design_microblaze_gpio_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_dlmb_v10_0 || ORIG_REF_NAME==design_microblaze_gpio_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_ilmb_v10_0/design_microblaze_gpio_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_ilmb_v10_0 || ORIG_REF_NAME==design_microblaze_gpio_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_dlmb_bram_if_cntlr_0/design_microblaze_gpio_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_microblaze_gpio_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_ilmb_bram_if_cntlr_0/design_microblaze_gpio_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_microblaze_gpio_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_lmb_bram_0/design_microblaze_gpio_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_lmb_bram_0 || ORIG_REF_NAME==design_microblaze_gpio_lmb_bram_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_mdm_1_0/design_microblaze_gpio_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_mdm_1_0 || ORIG_REF_NAME==design_microblaze_gpio_mdm_1_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_clk_wiz_1_0/design_microblaze_gpio_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_clk_wiz_1_0 || ORIG_REF_NAME==design_microblaze_gpio_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_rst_clk_wiz_1_100M_0/design_microblaze_gpio_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_microblaze_gpio_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_xbar_0/design_microblaze_gpio_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_xbar_0 || ORIG_REF_NAME==design_microblaze_gpio_xbar_0} -quiet] -quiet

# IP: bd/design_microblaze_gpio/ip/design_microblaze_gpio_microblaze_0_axi_periph_0/design_microblaze_gpio_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_microblaze_gpio_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_microblaze_gpio_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/design_microblaze_gpio/design_microblaze_gpio_ooc.xdc
