# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0.xci
# IP: The module: 'design_microblaze_gpio_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_gpio_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_gpio_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_gpio_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0.xci
# IP: The module: 'design_microblaze_gpio_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_gpio_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_gpio_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO2/Microblaze_GPIO2.srcs/sources_1/bd/design_microblaze_gpio/ip/design_microblaze_gpio_axi_uartlite_0_0/design_microblaze_gpio_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_gpio_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
