# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_project/MY_Basys-3-Master.xdc

# Block Designs: bd/upconter_design/upconter_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==upconter_design || ORIG_REF_NAME==upconter_design} -quiet] -quiet

# IP: bd/upconter_design/ip/upconter_design_FndController_0_0/upconter_design_FndController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==upconter_design_FndController_0_0 || ORIG_REF_NAME==upconter_design_FndController_0_0} -quiet] -quiet

# XDC: bd/upconter_design/upconter_design_ooc.xdc
