# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA_project/MY_Basys-3-Master.xdc

# Block Designs: bd/design_MB_GPIO_Timer_int/design_MB_GPIO_Timer_int.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int || ORIG_REF_NAME==design_MB_GPIO_Timer_int} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_0/design_MB_GPIO_Timer_int_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_dlmb_v10_0/design_MB_GPIO_Timer_int_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_dlmb_v10_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_ilmb_v10_0/design_MB_GPIO_Timer_int_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_ilmb_v10_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_dlmb_bram_if_cntlr_0/design_MB_GPIO_Timer_int_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_ilmb_bram_if_cntlr_0/design_MB_GPIO_Timer_int_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_lmb_bram_0/design_MB_GPIO_Timer_int_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_lmb_bram_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_lmb_bram_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_xbar_0/design_MB_GPIO_Timer_int_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_xbar_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_xbar_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_periph_0/design_MB_GPIO_Timer_int_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_xlconcat_0/design_MB_GPIO_Timer_int_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_mdm_1_0/design_MB_GPIO_Timer_int_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_mdm_1_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_mdm_1_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_clk_wiz_1_0/design_MB_GPIO_Timer_int_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_clk_wiz_1_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_rst_clk_wiz_1_100M_0/design_MB_GPIO_Timer_int_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_axi_uartlite_0_0/design_MB_GPIO_Timer_int_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_axi_uartlite_0_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_axi_gpio_0_0/design_MB_GPIO_Timer_int_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_axi_gpio_0_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_axi_timer_0_0/design_MB_GPIO_Timer_int_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_axi_timer_0_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_axi_gpio_1_0/design_MB_GPIO_Timer_int_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MB_GPIO_Timer_int_axi_gpio_1_0 || ORIG_REF_NAME==design_MB_GPIO_Timer_int_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/design_MB_GPIO_Timer_int/design_MB_GPIO_Timer_int_ooc.xdc
