# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0.xci
# IP: The module: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0.xci
# IP: The module: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/FPGA_project/Microblaze_GPIO_Timer_Interrupt/Microblaze_GPIO_Timer_Interrupt.srcs/sources_1/bd/design_MB_GPIO_Timer_int/ip/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0/design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MB_GPIO_Timer_int_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
